title: Settings
data:
  site_name: Octoper
  social:
    -
      name: Twitter
      url: 'https://twitter.com/itsoctoper'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/octoper'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:me@octoper.me'
      icon: site/social-icons/email.svg
    -
      name: LinkedIn
      url: 'https://www.linkedin.com/in/vaggelis-yfantis-2a559987/'
      icon: site/social-icons/linkedin.svg
