# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Composer Dependancies
      run: composer install
    - name: Install NPM Dependancies
      run: npm install
    - name: Build Website for Production
      run: npm run production
    - name: Build and Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build_production # The folder the action should deploy.
      
